server:
  port: 9500

spring:
  datasource:
    url: jdbc:mysql://lss.database.com:3306/library?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: library
    password: PMeiXKmzEMLb4NJi
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  main:
    allow-bean-definition-overriding: true
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .ftl
multipart:
  maxFileSize: 50Mb
  maxRequestSize: 50Mb
#  windows路径
#web:
#    upload-path: E:/Develop/Files/Photos/
#  linux路径
web:
    upload-path: /usr/java/library/files/photos/

mybatis-plus:
  typeEnumsPackage: com.baomidou.springboot.entity.enums
  configuration:
    ap-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
